---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQL
metadata:
  name: silly-demo
spec:
  id: silly-demo
  compositionRef:
    name: aws-postgresql
  parameters:
    version: "13.4"
    size: small
    namespace: production
  writeConnectionSecretToRef:
    name: silly-demo
    namespace: production
