---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 1.7.1
    helm:
      values: |
        alertmanager:
          ingress:
            enabled: true
            hosts:
            - alert-manager.34.239.188.67.nip.io
            ingressClassName: nginx
        server:
          ingress:
            enabled: true
            hosts:
            - prometheus.34.239.188.67.nip.io
            ingressClassName: nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
