server:
  ingress:
    enabled: true
  extraArgs:
  - --insecure
controller:
  args:
    appResyncPeriod: 30
configs:
  secret:
    argocdServerAdminPassword: "$2a$10$m3eTlEdRen0nS86c5Zph5u/bDFQMcWZYdG3NVdiyaACCqoxLJaz16"
    argocdServerAdminPasswordMtime: "2021-11-08T15:04:05Z"
